config/routes.rb
Rails.application.routes.draw do
	root 'contatos#index'
	resources :contatos, only: [:create, :show, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contato.rb
class Contato < ApplicationRecord
	has_many :telefones

	accepts_nested_attributes_for :telefones, reject_if: :all_blank, allow_destroy: true

	validates :nome, :email, :cargo, presence: true
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
	validates :email, uniqueness: true
	enum cargo: [:trainee, :membro, :diretor]
	  
end

app/models/telefone.rb
class Telefone < ApplicationRecord
	belongs_to :contato

	validates :numero, :tipo, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contatos_controller.rb
class ContatosController < ApplicationController

	def index
		@contato = Contato.new
		@contatos = Contato.all.order(:nome)
	end

	def create
		@contatos = Contato.all.order(:nome)
		@contato = Contato.new(contatos_parametros)
		
		if @contato.save
			render :create_success
		else
			render :create_error
		end
	end

	def show
		@contato = Contato.find(params[:id])
	end

	def destroy
		@contato = Contato.find(params[:id])
		@contato.delete
		redirect_to root_path
	end

	private

	def contatos_parametros
		params.require(:contato).permit(:nome, :email, :cargo, telefones_attributes: [:id, :numero, :tipo, :_destroy])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contatos_helper.rb
module ContatosHelper
end

app/views/contatos/_telefone_fields.html.erb
<div class="nested-fields">
	<div class="form-group row">
		<div class="col-sm-4">
			<%=  f.text_field :tipo, placeholder: "Tipo", class: "form-control" %>
		</div>	
		<div class="col-sm-6">			
			<%= f.text_field :numero, placeholder: "Numero", class: "form-control" %>
		</div>
		<div class="col-sm-2">	
			<%= link_to_remove_association "remover", f, class: "btn btn-default" %>
		</div>	
		<br>
	</div>	
</div>

app/views/contatos/create_error.js.erb
function Erro() {
	//apagar o valor dos inputs
	$("input").val("");

	let errorsArray = <%= raw @contato.errors.full_messages %>;
	let errorMessage = '';
	errorsArray.map((message) => {
		errorMessage += message + ", "
	});



	swal("Erro!!", errorMessage, "error");
}


Erro();

app/views/contatos/create_success.js.erb
function Sucesso() {
	//apagar o valor dos inputs
	$("input").val("");

	// nome do contato
	let name = "<%= @contato.nome %>"

	//flag para ver se a linha ja foi colocada
	let flag = 0;

	// contrução da linha que vamos inserir
	let novaLinha = '';
	novaLinha += "<tr><td><%= j(link_to @contato.nome, contato_path(@contato.id)) %></td>";
	novaLinha += "<td><%= j(@contato.email) %></td>";
	novaLinha += "<td><%= j(link_to "Apagar", contato_path(@contato.id), method: :delete) %></td></tr>"

	// grava caso a lista seja vazia
	if ($('tbody  > tr').length == 0) {
		$('tbody').append(novaLinha);
		flag = 1;
	}

	// bloco para encontrar o local certo
	if (flag == 0) {
		$('tbody  > tr').each((i, tr) => {
			let td = $(tr).find('td:first');
			let a = $(td).find('a');
			let text = $(a).html();
			if (text >= name) {
				$(tr).before(novaLinha);
				flag = 1;
				return false;
			}
		});
	}

	// bloco que grava a linha no final
	if (flag == 0) {
		$('tbody > tr:last').after(novaLinha);
		flag = 1;
	}

	swal("Sucesso!!", `${name} foi adicionado em sua lista`, "success");
}


Sucesso();

app/views/contatos/index.html.erb
<div class="container">
	<div class="col-sm-6">
		<h1>Cadastro</h1>
		<h3><%= notice %></h3>
		<%= form_for @contato, remote: true do |f|%>
			
			<div class="form-group">
				<%= f.label :nome %>
				<%= f.text_field :nome, class: "form-control" %>
			</div>

			<div class="form-group">
				<%= f.label :email %>
				<%= f.email_field :email, class: "form-control" %>
			</div>
			
			<div id="telefones">
				<%= f.fields_for :telefones do |t| %>
					<%= render 'telefone_fields', f: t %>
				<% end %>
				<%= link_to_add_association '+', f, :telefones, class: "btn btn-default" %>
			</div>
			<br>

			<div class="form-group">
				<%=f.label :cargo%>
				<%=f.select :cargo, options_for_select(Contato.cargos.keys), {}, {:class => "form-control"} %>
			</div>

			<%= f.submit "Cadastrar", class: "btn btn-default" %>
		<%end%>	
	</div>
	<div class="col-sm-6">
		<h1>Lista de contatos</h1>
		<table class="table">
			<thead>
				<tr>
					<th>Nome</th>
					<th>Email</th>
					<th>Delete</th>
				</tr>
			</thead>
			<tbody>
				<% @contatos.each do |contato| %>
					<tr>
						<td><%= link_to contato.nome, contato_path(contato.id) %></td>
						<td><%= contato.email %></td>
						<td><%= link_to "Apagar", contato_path(contato.id), method: :delete %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/contatos/show.html.erb
<div class="container">
	<h1>Contato</h1>
	<p><%= @contato.nome %></p>
	<p><%= @contato.email %></p>
	<% @contato.telefones.each do |t| %>
		<p>
			<%= t.tipo %>
			<%= t.numero %>
		</p>
	<% end %>
	<p><% @contato.cargo %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContatosDojo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>